// Приклад структури. Тут має бути 800 пар {en, uk}.
const WORDS_A1 = [
  //1
  { en: "apple", uk: "яблуко" },
  { en: "banana", uk: "банан" },
  { en: "orange", uk: "апельсин" },
  { en: "pear", uk: "груша" },
  { en: "grape", uk: "виноград" },
  { en: "watermelon", uk: "кавун" },
  { en: "strawberry", uk: "полуниця" },
  { en: "cherry", uk: "вишня" },
  { en: "lemon", uk: "лимон" },
  { en: "peach", uk: "персик" },
  { en: "tomato", uk: "помідор" },
  { en: "cucumber", uk: "огірок" },
  { en: "potato", uk: "картопля" },
  { en: "carrot", uk: "морква" },
  { en: "onion", uk: "цибуля" },
  { en: "bread", uk: "хліб" },
  { en: "milk", uk: "молоко" },
  { en: "water", uk: "вода" },
  { en: "tea", uk: "чай" },
  { en: "coffee", uk: "кава" },
  { en: "meat", uk: "м'ясо" },
  { en: "chicken", uk: "курка" },
  { en: "fish", uk: "риба" },
  { en: "egg", uk: "яйце" },
  { en: "cheese", uk: "сир" },
  { en: "butter", uk: "масло" },
  { en: "sugar", uk: "цукор" },
  { en: "salt", uk: "сіль" },
  { en: "rice", uk: "рис" },
  { en: "soup", uk: "суп" },
  { en: "salad", uk: "салат" },
  { en: "cake", uk: "торт" },
  { en: "cookie", uk: "печиво" },
  { en: "ice cream", uk: "морозиво" },
  { en: "breakfast", uk: "сніданок" },
  { en: "lunch", uk: "обід" },
  { en: "dinner", uk: "вечеря" },
  { en: "school", uk: "школа" },
  { en: "book", uk: "книга" },
  { en: "pen", uk: "ручка" },
  { en: "pencil", uk: "олівець" },
  { en: "bag", uk: "сумка" },
  { en: "table", uk: "стіл" },
  { en: "chair", uk: "стілець" },
  { en: "door", uk: "двері" },
  { en: "window", uk: "вікно" },
  { en: "house", uk: "будинок" },
  { en: "room", uk: "кімната" },
  { en: "bed", uk: "ліжко" },
  { en: "sofa", uk: "диван" },
  { en: "kitchen", uk: "кухня" },
  { en: "bathroom", uk: "ванна кімната" },
  { en: "floor", uk: "підлога" },
  { en: "wall", uk: "стіна" },
  { en: "roof", uk: "дах" },
  { en: "family", uk: "сім'я" },
  { en: "mother", uk: "мати" },
  { en: "father", uk: "батько" },
  { en: "sister", uk: "сестра" },
  { en: "brother", uk: "брат" },
  { en: "grandmother", uk: "бабуся" },
  { en: "grandfather", uk: "дідусь" },
  { en: "aunt", uk: "тітка" },
  { en: "uncle", uk: "дядько" },
  { en: "cousin", uk: "двоюрідний брат/сестра" },
  { en: "son", uk: "син" },
  { en: "daughter", uk: "дочка" },
  { en: "child", uk: "дитина" },
  { en: "friend", uk: "друг" },
  { en: "boy", uk: "хлопчик" },
  { en: "girl", uk: "дівчинка" },
  { en: "man", uk: "чоловік" },
  { en: "woman", uk: "жінка" },
  { en: "people", uk: "люди" },
  { en: "dog", uk: "собака" },
  { en: "cat", uk: "кіт" },
  { en: "bird", uk: "птах" },
  { en: "cow", uk: "корова" },
  { en: "horse", uk: "кінь" },
  { en: "sheep", uk: "вівця" },
  { en: "pig", uk: "свиня" },
  { en: "mouse", uk: "миша" },
  { en: "fish", uk: "риба" },
  { en: "sun", uk: "сонце" },
  { en: "moon", uk: "місяць" },
  { en: "star", uk: "зірка" },
  { en: "sky", uk: "небо" },
  { en: "cloud", uk: "хмара" },
  { en: "rain", uk: "дощ" },
  { en: "snow", uk: "сніг" },
  { en: "wind", uk: "вітер" },
  { en: "tree", uk: "дерево" },
  { en: "flower", uk: "квітка" },
  { en: "grass", uk: "трава" },
  { en: "river", uk: "річка" },
  { en: "sea", uk: "море" },
  { en: "lake", uk: "озеро" },
  { en: "mountain", uk: "гора" },
  { en: "road", uk: "дорога" },
  { en: "car", uk: "автомобіль" },
  { en: "bus", uk: "автобус" },
  { en: "train", uk: "поїзд" },
  { en: "plane", uk: "літак" },
  { en: "ship", uk: "корабель" },
  { en: "bicycle", uk: "велосипед" },
  { en: "red", uk: "червоний" },
  { en: "blue", uk: "синій" },
  { en: "green", uk: "зелений" },
  { en: "yellow", uk: "жовтий" },
  { en: "black", uk: "чорний" },
  { en: "white", uk: "білий" },
  { en: "brown", uk: "коричневий" },
  { en: "pink", uk: "рожевий" },
  { en: "orange (color)", uk: "помаранчевий" },
  { en: "gray", uk: "сірий" },
  { en: "one", uk: "один" },
  { en: "two", uk: "два" },
  { en: "three", uk: "три" },
  { en: "four", uk: "чотири" },
  { en: "five", uk: "п’ять" },
  { en: "six", uk: "шість" },
  { en: "seven", uk: "сім" },
  { en: "eight", uk: "вісім" },
  { en: "nine", uk: "дев’ять" },
  { en: "ten", uk: "десять" },
  { en: "Monday", uk: "понеділок" },
  { en: "Tuesday", uk: "вівторок" },
  { en: "Wednesday", uk: "середа" },
  { en: "Thursday", uk: "четвер" },
  { en: "Friday", uk: "п’ятниця" },
  { en: "Saturday", uk: "субота" },
  { en: "Sunday", uk: "неділя" },
  { en: "January", uk: "січень" },
  { en: "February", uk: "лютий" },
  { en: "March", uk: "березень" },
  { en: "April", uk: "квітень" },
  { en: "May", uk: "травень" },
  { en: "June", uk: "червень" },
  { en: "July", uk: "липень" },
  { en: "August", uk: "серпень" },
  { en: "September", uk: "вересень" },
  { en: "October", uk: "жовтень" },
  { en: "November", uk: "листопад" },
  { en: "December", uk: "грудень" },

  // ДІЄСЛОВА (основні)
  { en: "be", uk: "бути" },
  { en: "have", uk: "мати" },
  { en: "do", uk: "робити" },
  { en: "go", uk: "йти" },
  { en: "come", uk: "приходити" },
  { en: "leave", uk: "залишати" },
  { en: "live", uk: "жити" },
  { en: "work", uk: "працювати" },
  { en: "study", uk: "вчитися" },
  { en: "learn", uk: "вивчати" },
  { en: "speak", uk: "говорити" },
  { en: "say", uk: "сказати" },
  { en: "tell", uk: "розповідати" },
  { en: "ask", uk: "питати" },
  { en: "answer", uk: "відповідати" },
  { en: "listen", uk: "слухати" },
  { en: "hear", uk: "чути" },
  { en: "see", uk: "бачити" },
  { en: "look", uk: "дивитися" },
  { en: "watch", uk: "спостерігати" },
  { en: "read", uk: "читати" },
  { en: "write", uk: "писати" },
  { en: "play", uk: "грати" },
  { en: "eat", uk: "їсти" },
  { en: "drink", uk: "пити" },
  { en: "sleep", uk: "спати" },
  { en: "wake up", uk: "прокидатися" },
  { en: "open", uk: "відкривати" },
  { en: "close", uk: "закривати" },
  { en: "sit", uk: "сидіти" },
  { en: "stand", uk: "стояти" },
  { en: "walk", uk: "ходити" },
  { en: "run", uk: "бігти" },
  { en: "swim", uk: "плавати" },
  { en: "drive", uk: "водити" },
  { en: "ride", uk: "їхати верхи / на транспорті" },
  { en: "fly", uk: "літати" },
  { en: "buy", uk: "купувати" },
  { en: "sell", uk: "продавати" },
  { en: "make", uk: "робити/виготовляти" },
  { en: "help", uk: "допомагати" },
  { en: "use", uk: "використовувати" },
  { en: "need", uk: "потребувати" },
  { en: "want", uk: "хотіти" },
  { en: "like", uk: "подобатися" },
  { en: "love", uk: "любити" },
  { en: "hate", uk: "ненавидіти" },
  { en: "wait", uk: "чекати" },
  { en: "start", uk: "починати" },
  { en: "finish", uk: "закінчувати" },
  { en: "stop", uk: "зупинятися" },
  { en: "move", uk: "рухатися" },
  { en: "stay", uk: "залишатися" },
  { en: "travel", uk: "подорожувати" },
  { en: "visit", uk: "відвідувати" },
  { en: "show", uk: "показувати" },
  { en: "call", uk: "дзвонити/називати" },
  { en: "meet", uk: "зустрічати" },
  { en: "remember", uk: "пам'ятати" },
  { en: "forget", uk: "забувати" },
  { en: "understand", uk: "розуміти" },
  { en: "know", uk: "знати" },
  { en: "learn", uk: "вчитися" },

  // ПРИКМЕТНИКИ
  { en: "big", uk: "великий" },
  { en: "small", uk: "маленький" },
  { en: "long", uk: "довгий" },
  { en: "short", uk: "короткий/низький" },
  { en: "tall", uk: "високий (про людину)" },
  { en: "new", uk: "новий" },
  { en: "old", uk: "старий" },
  { en: "young", uk: "молодий" },
  { en: "good", uk: "хороший" },
  { en: "bad", uk: "поганий" },
  { en: "happy", uk: "щасливий" },
  { en: "sad", uk: "сумний" },
  { en: "angry", uk: "злий" },
  { en: "hungry", uk: "голодний" },
  { en: "thirsty", uk: "спраглий" },
  { en: "hot", uk: "гарячий" },
  { en: "cold", uk: "холодний" },
  { en: "warm", uk: "теплий" },
  { en: "beautiful", uk: "красивий" },
  { en: "ugly", uk: "потворний" },
  { en: "easy", uk: "легкий" },
  { en: "difficult", uk: "важкий" },
  { en: "fast", uk: "швидкий" },
  { en: "slow", uk: "повільний" },
  { en: "clean", uk: "чистий" },
  { en: "dirty", uk: "брудний" },
  { en: "rich", uk: "багатий" },
  { en: "poor", uk: "бідний" },
  { en: "strong", uk: "сильний" },
  { en: "weak", uk: "слабкий" },
  { en: "funny", uk: "смішний" },
  { en: "serious", uk: "серйозний" },
  { en: "important", uk: "важливий" },
  { en: "free", uk: "вільний/безкоштовний" },
  { en: "busy", uk: "зайнятий" },
  { en: "same", uk: "однаковий" },
  { en: "different", uk: "різний" },
  { en: "true", uk: "правдивий" },
  { en: "false", uk: "неправдивий" },
  
  // ПОШИРЕНІ ВИРАЗИ
  { en: "hello", uk: "привіт" },
  { en: "hi", uk: "привіт" },
  { en: "good morning", uk: "доброго ранку" },
  { en: "good afternoon", uk: "доброго дня" },
  { en: "good evening", uk: "доброго вечора" },
  { en: "good night", uk: "надобраніч" },
  { en: "bye", uk: "бувай" },
  { en: "see you", uk: "побачимось" },
  { en: "thank you", uk: "дякую" },
  { en: "thanks", uk: "дякую" },
  { en: "please", uk: "будь ласка" },
  { en: "sorry", uk: "вибач" },
  { en: "excuse me", uk: "перепрошую" },
  { en: "yes", uk: "так" },
  { en: "no", uk: "ні" },
  { en: "maybe", uk: "можливо" },
  { en: "of course", uk: "звісно" },
  { en: "I don't know", uk: "я не знаю" },
  { en: "I don't understand", uk: "я не розумію" },
  { en: "How are you?", uk: "Як справи?" },
  { en: "I'm fine", uk: "У мене все добре" },
  { en: "What's your name?", uk: "Як тебе звати?" },
  { en: "My name is...", uk: "Мене звати..." },
  { en: "How old are you?", uk: "Скільки тобі років?" },
  { en: "I am ... years old", uk: "Мені ... років" },
  { en: "Where are you from?", uk: "Звідки ти?" },
  { en: "I am from...", uk: "Я з..." },
  { en: "I like it", uk: "Мені це подобається" },
  { en: "I don't like it", uk: "Мені це не подобається" },
  { en: "Can you help me?", uk: "Ти можеш мені допомогти?" },
  { en: "What is this?", uk: "Що це?" },
  { en: "I need...", uk: "Мені потрібно..." },
  { en: "I want...", uk: "Я хочу..." },

  // ОДЯГ
  { en: "clothes", uk: "одяг" },
  { en: "shirt", uk: "сорочка" },
  { en: "T-shirt", uk: "футболка" },
  { en: "dress", uk: "сукня" },
  { en: "skirt", uk: "спідниця" },
  { en: "trousers", uk: "штани" },
  { en: "jeans", uk: "джинси" },
  { en: "shorts", uk: "шорти" },
  { en: "jacket", uk: "куртка" },
  { en: "coat", uk: "пальто" },
  { en: "sweater", uk: "светр" },
  { en: "shoes", uk: "взуття" },
  { en: "boots", uk: "чоботи" },
  { en: "sandals", uk: "сандалі" },
  { en: "socks", uk: "шкарпетки" },
  { en: "hat", uk: "капелюх" },
  { en: "cap", uk: "кепка" },
  { en: "scarf", uk: "шарф" },
  { en: "gloves", uk: "рукавички" },
  { en: "belt", uk: "пояс" },
  { en: "bag", uk: "сумка" },
  { en: "backpack", uk: "рюкзак" },
  { en: "watch", uk: "годинник" },
  { en: "glasses", uk: "окуляри" },

  // МЕБЛІ ТА ПРЕДМЕТИ ВДОМА
  { en: "lamp", uk: "лампа" },
  { en: "mirror", uk: "дзеркало" },
  { en: "cup", uk: "чашка" },
  { en: "glass", uk: "склянка" },
  { en: "plate", uk: "тарілка" },
  { en: "fork", uk: "виделка" },
  { en: "spoon", uk: "ложка" },
  { en: "knife", uk: "ніж" },
  { en: "bed", uk: "ліжко" },
  { en: "pillow", uk: "подушка" },
  { en: "blanket", uk: "ковдра" },
  { en: "toilet", uk: "туалет" },
  { en: "shower", uk: "душ" },
  { en: "soap", uk: "мило" },
  { en: "towel", uk: "рушник" },
  { en: "fridge", uk: "холодильник" },
  { en: "oven", uk: "піч" },
  { en: "stove", uk: "плита" },
  { en: "television", uk: "телевізор" },
  { en: "computer", uk: "комп’ютер" },
  { en: "phone", uk: "телефон" },
  { en: "radio", uk: "радіо" },
  { en: "clock", uk: "годинник" },

  // МІСТО
  { en: "city", uk: "місто" },
  { en: "village", uk: "село" },
  { en: "street", uk: "вулиця" },
  { en: "square", uk: "площа" },
  { en: "park", uk: "парк" },
  { en: "shop", uk: "магазин" },
  { en: "supermarket", uk: "супермаркет" },
  { en: "market", uk: "ринок" },
  { en: "restaurant", uk: "ресторан" },
  { en: "cafe", uk: "кафе" },
  { en: "school", uk: "школа" },
  { en: "university", uk: "університет" },
  { en: "hospital", uk: "лікарня" },
  { en: "pharmacy", uk: "аптека" },
  { en: "bank", uk: "банк" },
  { en: "post office", uk: "пошта" },
  { en: "hotel", uk: "готель" },
  { en: "cinema", uk: "кінотеатр" },
  { en: "theatre", uk: "театр" },
  { en: "museum", uk: "музей" },
  { en: "church", uk: "церква" },
  { en: "station", uk: "станція" },
  { en: "airport", uk: "аеропорт" },
  { en: "bridge", uk: "міст" },
  { en: "shop assistant", uk: "продавець" },

  // ЧАС
  { en: "time", uk: "час" },
  { en: "day", uk: "день" },
  { en: "week", uk: "тиждень" },
  { en: "month", uk: "місяць" },
  { en: "year", uk: "рік" },
  { en: "today", uk: "сьогодні" },
  { en: "tomorrow", uk: "завтра" },
  { en: "yesterday", uk: "вчора" },
  { en: "morning", uk: "ранок" },
  { en: "afternoon", uk: "після обіду" },
  { en: "evening", uk: "вечір" },
  { en: "night", uk: "ніч" },
  { en: "minute", uk: "хвилина" },
  { en: "hour", uk: "година" },
  { en: "holiday", uk: "свято/відпустка" },
  { en: "birthday", uk: "день народження" },

  // ЧИСЛА 11–100
  { en: "eleven", uk: "одинадцять" },
  { en: "twelve", uk: "дванадцять" },
  { en: "thirteen", uk: "тринадцять" },
  { en: "fourteen", uk: "чотирнадцять" },
  { en: "fifteen", uk: "п’ятнадцять" },
  { en: "sixteen", uk: "шістнадцять" },
  { en: "seventeen", uk: "сімнадцять" },
  { en: "eighteen", uk: "вісімнадцять" },
  { en: "nineteen", uk: "дев’ятнадцять" },
  { en: "twenty", uk: "двадцять" },
  { en: "thirty", uk: "тридцять" },
  { en: "forty", uk: "сорок" },
  { en: "fifty", uk: "п’ятдесят" },
  { en: "sixty", uk: "шістдесят" },
  { en: "seventy", uk: "сімдесят" },
  { en: "eighty", uk: "вісімдесят" },
  { en: "ninety", uk: "дев’яносто" },
  { en: "one hundred", uk: "сто" },

  // ПРИРОДА
  { en: "nature", uk: "природа" },
  { en: "world", uk: "світ" },
  { en: "earth", uk: "земля" },
  { en: "sky", uk: "небо" },
  { en: "sun", uk: "сонце" },
  { en: "moon", uk: "місяць" },
  { en: "star", uk: "зірка" },
  { en: "cloud", uk: "хмара" },
  { en: "rain", uk: "дощ" },
  { en: "snow", uk: "сніг" },
  { en: "wind", uk: "вітер" },
  { en: "storm", uk: "буря" },
  { en: "river", uk: "річка" },
  { en: "lake", uk: "озеро" },
  { en: "sea", uk: "море" },
  { en: "ocean", uk: "океан" },
  { en: "mountain", uk: "гора" },
  { en: "forest", uk: "ліс" },
  { en: "tree", uk: "дерево" },
  { en: "flower", uk: "квітка" },
  { en: "grass", uk: "трава" },
  { en: "beach", uk: "пляж" },
  { en: "island", uk: "острів" },
  { en: "desert", uk: "пустеля" },

  // ТВАРИНИ
  { en: "animal", uk: "тварина" },
  { en: "dog", uk: "собака" },
  { en: "cat", uk: "кіт" },
  { en: "bird", uk: "птах" },
  { en: "fish", uk: "риба" },
  { en: "horse", uk: "кінь" },
  { en: "cow", uk: "корова" },
  { en: "pig", uk: "свиня" },
  { en: "sheep", uk: "вівця" },
  { en: "chicken", uk: "курка" },
  { en: "duck", uk: "качка" },
  { en: "goat", uk: "коза" },
  { en: "lion", uk: "лев" },
  { en: "tiger", uk: "тигр" },
  { en: "elephant", uk: "слон" },
  { en: "monkey", uk: "мавпа" },
  { en: "bear", uk: "ведмідь" },
  { en: "wolf", uk: "вовк" },
  { en: "fox", uk: "лисиця" },
  { en: "mouse", uk: "миша" },
  { en: "rabbit", uk: "кролик" },
  { en: "snake", uk: "змія" },
  { en: "frog", uk: "жаба" },
  { en: "insect", uk: "комаха" },

  // СПОРТ
  { en: "sport", uk: "спорт" },
  { en: "game", uk: "гра" },
  { en: "football", uk: "футбол" },
  { en: "basketball", uk: "баскетбол" },
  { en: "tennis", uk: "теніс" },
  { en: "volleyball", uk: "волейбол" },
  { en: "swimming", uk: "плавання" },
  { en: "running", uk: "біг" },
  { en: "cycling", uk: "їзда на велосипеді" },
  { en: "skiing", uk: "лижний спорт" },
  { en: "skating", uk: "катання на ковзанах" },
  { en: "gym", uk: "спортзал" },
  { en: "ball", uk: "м’яч" },
  { en: "team", uk: "команда" },
  { en: "player", uk: "гравець" },
  { en: "winner", uk: "переможець" },
  { en: "loser", uk: "програвший" },
  { en: "trainer", uk: "тренер" },
  { en: "match", uk: "матч" },
  { en: "goal", uk: "гол" },

  // ТІЛО ЛЮДИНИ
  { en: "body", uk: "тіло" },
  { en: "head", uk: "голова" },
  { en: "face", uk: "обличчя" },
  { en: "eye", uk: "око" },
  { en: "ear", uk: "вухо" },
  { en: "nose", uk: "ніс" },
  { en: "mouth", uk: "рот" },
  { en: "tooth", uk: "зуб" },
  { en: "tongue", uk: "язик" },
  { en: "hair", uk: "волосся" },
  { en: "hand", uk: "рука (кисть)" },
  { en: "arm", uk: "рука" },
  { en: "leg", uk: "нога" },
  { en: "foot", uk: "стопа" },
  { en: "knee", uk: "коліно" },
  { en: "finger", uk: "палець" },
  { en: "back", uk: "спина" },
  { en: "stomach", uk: "живіт" },
  { en: "heart", uk: "серце" },
  { en: "brain", uk: "мозок" },

  // ПОЧУТТЯ ТА СТАН
  { en: "happy", uk: "щасливий" },
  { en: "sad", uk: "сумний" },
  { en: "angry", uk: "злий" },
  { en: "tired", uk: "втомлений" },
  { en: "hungry", uk: "голодний" },
  { en: "thirsty", uk: "спраглий" },
  { en: "hot", uk: "спекотно" },
  { en: "cold", uk: "холодно" },
  { en: "well", uk: "здоровий" },
  { en: "sick", uk: "хворий" },
  { en: "afraid", uk: "наляканий" },
  { en: "surprised", uk: "здивований" },
  { en: "bored", uk: "нудьгуючий" },
  { en: "interested", uk: "зацікавлений" },
  { en: "love", uk: "любов" },
  { en: "like", uk: "подобатися" },
  { en: "hate", uk: "ненавидіти" },
  { en: "smile", uk: "усмішка" },
  { en: "cry", uk: "плакати" },

  // ПОБУТ
  { en: "work", uk: "робота" },
  { en: "job", uk: "професія" },
  { en: "money", uk: "гроші" },
  { en: "price", uk: "ціна" },
  { en: "shop", uk: "магазин" },
  { en: "food", uk: "їжа" },
  { en: "drink", uk: "напій" },
  { en: "bread", uk: "хліб" },
  { en: "butter", uk: "масло" },
  { en: "cheese", uk: "сир" },
  { en: "meat", uk: "м’ясо" },
  { en: "chicken", uk: "курятина" },
  { en: "egg", uk: "яйце" },
  { en: "soup", uk: "суп" },
  { en: "rice", uk: "рис" },
  { en: "potato", uk: "картопля" },
  { en: "tomato", uk: "помідор" },
  { en: "cucumber", uk: "огірок" },
  { en: "carrot", uk: "морква" },
  { en: "apple", uk: "яблуко" },
  { en: "banana", uk: "банан" },
  { en: "orange", uk: "апельсин" },
  { en: "lemon", uk: "лимон" },
  { en: "water", uk: "вода" },
  { en: "milk", uk: "молоко" },
  { en: "tea", uk: "чай" },
  { en: "coffee", uk: "кава" },
  { en: "sugar", uk: "цукор" },
  { en: "salt", uk: "сіль" },
  { en: "pepper", uk: "перець" },
  { en: "oil", uk: "олія" },
  { en: "cake", uk: "торт" },
  { en: "ice cream", uk: "морозиво" },
  { en: "chocolate", uk: "шоколад" },
  { en: "fruit", uk: "фрукти" },
  { en: "vegetable", uk: "овочі" }
];
